version:  "3"
services:
  react:
    build:
      context: .
      args:
        SSHPASS: ${SSHPASS}

    ports: # Need to open these ports to work with Expo
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "2222:22"

    environment:
      #The following can be edited in the .env file.
      EXPO_DEVTOOLS_LISTEN_ADDRESS: ${localhost} #Needed to expose Devtools to the host machine
      REACT_NATIVE_PACKAGER_HOSTNAME: ${myip} # Needed to expose expo developer tools to the host

    volumes:
      - ./app:/var/www/
    tty: true
